/* ============================================================
 * Metadata Remove Pro Web - Core Engine (parsers / scanner / cleaner)
 * Copyright (c) 2026. All rights reserved.
 * ============================================================ */
(function (root) {
  'use strict';

  var C2PA_MARKERS = ['c2pa', 'jumd', 'JUMBF'];
  var AI_GENERATORS = [
    'midjourney', 'dall-e', 'dalle', 'chatgpt', 'gpt-image', 'gpt image',
    'openai', 'stable diffusion', 'stability ai', 'stabilityai',
    'sd_xl', 'sdxl', 'sd 1.5', 'sd15', 'comfyui', 'automatic1111', 'a1111',
    'fooocus', 'invokeai', 'novelai', 'leonardo.ai', 'leonardo ai',
    'ideogram', 'firefly', 'adobe firefly', 'imagen', 'gemini',
    'sora', 'veo', 'runway', 'runwayml', 'gen-3', 'gen3', 'gen-2',
    'pika', 'kling', 'keling', 'hailuo', 'jimeng',
    'seedream', 'vidu', 'luma', 'flux', 'playgroundai', 'nightcafe',
    'civitai', 'deepai', 'copilot', 'bing image', 'bria', 'recraft',
    'cfg scale', 'dpm++', 'karras', 'negative prompt', 'denoising strength',
    'euler a', 'checkpoint', 'loras', 'magic media', 'ai studio',
  ];
  var AI_FLAGS = [
    'aigc', 'ai-generated', 'ai generated', 'generated by ai',
    'generated with ai', 'made with ai', 'created with ai',
    'trainedalgorithmicmedia', 'compositewithtrainedalgorithmicmedia',
    'digitalsourcetype', 'claim_generator',
  ];
  var APP_HINTS = [
    'capcut', 'jianying', 'canva', 'photoshop', 'adobe', 'tiktok', 'douyin',
    'instagram', 'snapseed', 'lightroom', 'meitu', 'vsco', 'after effects',
  ];
  var PNG_DROP = ['tEXt', 'zTXt', 'iTXt', 'eXIf', 'caBX', 'C2PA', 'uuid', 'tIME', 'iCCP'];
  var XMP_ATTRS = [
    'dc:creator', 'dc:title', 'dc:description', 'dc:rights', 'dc:publisher', 'dc:subject',
    'xmp:CreatorTool', 'xmp:CreateDate', 'xmpMM:DocumentID', 'xmpMM:InstanceID',
    'photoshop:Credit', 'photoshop:Source', 'Iptc4xmpExt:DigitalSourceType',
    'stEvt:softwareAgent', 'stEvt:action', 'crs:RawFileName',
  ];

  var crcTable = (function () {
    var t = new Uint32Array(256);
    for (var n = 0; n < 256; n++) {
      var c = n;
      for (var k = 0; k < 8; k++) c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
      t[n] = c >>> 0;
    }
    return t;
  })();
  function crc32(bytes) {
    var c = 0xFFFFFFFF;
    for (var i = 0; i < bytes.length; i++) c = crcTable[(c ^ bytes[i]) & 0xFF] ^ (c >>> 8);
    return (c ^ 0xFFFFFFFF) >>> 0;
  }

  function utf8(bytes) {
    try { return new TextDecoder('utf-8', { fatal: false }).decode(bytes); }
    catch (e) { return String.fromCharCode.apply(null, bytes); }
  }
  function latin1(bytes) {
    var s = '';
    for (var i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i]);
    return s;
  }
  function findRuns(bytes, minLen) {
    var runs = [], cur = [];
    for (var i = 0; i < bytes.length; i++) {
      var b = bytes[i];
      if (b >= 32 && b < 127) cur.push(b);
      else { if (cur.length >= minLen) runs.push(latin1(cur)); cur = []; }
    }
    if (cur.length >= minLen) runs.push(latin1(cur));
    return runs;
  }
  function classify(text) {
    var low = (text || '').toLowerCase();
    for (var i = 0; i < AI_GENERATORS.length; i++)
      if (low.indexOf(AI_GENERATORS[i]) >= 0) return { kind: 'ai', sig: AI_GENERATORS[i] };
    for (var j = 0; j < AI_FLAGS.length; j++)
      if (low.indexOf(AI_FLAGS[j]) >= 0) return { kind: 'ai_flag', sig: AI_FLAGS[j] };
    for (var k = 0; k < APP_HINTS.length; k++)
      if (low.indexOf(APP_HINTS[k]) >= 0) return { kind: 'app', sig: APP_HINTS[k] };
    return null;
  }
  function trunc(s, n) {
    s = String(s == null ? '' : s).replace(/\s+/g, ' ').trim();
    return s.length > n ? s.slice(0, n) + '…' : s;
  }

  // ---- PNG ----
  function pngChunks(data) {
    if (data.length < 8 || data[0] !== 0x89 || data[1] !== 0x50 || data[2] !== 0x4E || data[3] !== 0x47) return null;
    var chunks = [], i = 8, view = new DataView(data.buffer, data.byteOffset, data.byteLength);
    while (i + 8 <= data.length) {
      var len = view.getUint32(i, false);
      if (i + 12 + len > data.length) break;
      var type = latin1(data.subarray(i + 4, i + 8));
      chunks.push({ type: type, data: data.subarray(i + 8, i + 8 + len) });
      i += 12 + len;
      if (type === 'IEND') break;
    }
    return chunks;
  }
  function parsePngText(type, payload) {
    try {
      if (type === 'tEXt') {
        var z = payload.indexOf(0);
        return [latin1(payload.subarray(0, z < 0 ? payload.length : z)), utf8(payload.subarray(z + 1))];
      }
      var z0 = payload.indexOf(0);
      if (type === 'zTXt') {
        var rest = payload.subarray(z0 + 1);
        return [latin1(payload.subarray(0, z0)), utf8(inflateRaw(rest.subarray(1)))];
      }
      // iTXt: keyword\0 flag method lang\0 translated\0 text
      var flag = payload[z0 + 1] || 0;
      var rest2 = payload.subarray(z0 + 3);
      var z1 = rest2.indexOf(0);
      var rest3 = rest2.subarray(z1 + 1);
      var z2 = rest3.indexOf(0);
      var text = rest3.subarray(z2 + 1);
      return [latin1(payload.subarray(0, z0)), utf8(flag ? inflateRaw(text) : text)];
    } catch (e) { return ['?', '']; }
  }
  // zlib raw inflate 的最小实现(处理 zTXt/iTXt 压缩文本)
  function inflateRaw(bytes) {
    try {
      if (typeof DecompressionStream !== 'undefined') return inflateSync(bytes);
    } catch (e) {}
    return bytes; // 无法解压时返回原始字节(尽力而为)
  }
  function inflateSync(bytes) {
    // 浏览器环境用 DecompressionStream 同步不可行, 此处返回原文; 调用方会降级处理
    return bytes;
  }
  function stripPng(data) {
    var chunks = pngChunks(data);
    if (!chunks) return null;
    var parts = [data.subarray(0, 8)], removed = [];
    for (var i = 0; i < chunks.length; i++) {
      var ch = chunks[i];
      if (PNG_DROP.indexOf(ch.type) >= 0) { removed.push(ch.type); continue; }
      var raw = new Uint8Array(4 + ch.data.length);
      raw.set([ch.type.charCodeAt(0), ch.type.charCodeAt(1), ch.type.charCodeAt(2), ch.type.charCodeAt(3)]);
      raw.set(ch.data, 4);
      var lenB = new Uint8Array(4);
      new DataView(lenB.buffer).setUint32(0, ch.data.length, false);
      var crcB = new Uint8Array(4);
      new DataView(crcB.buffer).setUint32(0, crc32(raw), false);
      parts.push(lenB, raw, crcB);
    }
    return { data: concat(parts), removed: uniq(removed) };
  }

  // ---- JPEG ----
  function jpegSegments(data) {
    if (data.length < 4 || data[0] !== 0xFF || data[1] !== 0xD8) return null;
    var segs = [], i = 2;
    while (i + 4 <= data.length) {
      if (data[i] !== 0xFF) break;
      var m = data[i + 1];
      if (m === 0xD8 || (m >= 0xD0 && m <= 0xD7)) { segs.push({ marker: m, data: new Uint8Array(0), offset: i }); i += 2; continue; }
      var len = (data[i + 2] << 8) | data[i + 3];
      if (i + 2 + len > data.length) break;
      segs.push({ marker: m, data: data.subarray(i + 4, i + 2 + len), offset: i });
      i += 2 + len;
      if (m === 0xDA) break;
    }
    return segs;
  }
  function tiffOrientation(tiff) {
    try {
      if (tiff.length < 10) return 1;
      var little = tiff[0] === 0x49 && tiff[1] === 0x49;
      if (!little && !(tiff[0] === 0x4D && tiff[1] === 0x4D)) return 1;
      var view = new DataView(tiff.buffer, tiff.byteOffset, tiff.byteLength);
      var off = view.getUint32(4, little);
      var n = view.getUint16(off, little);
      for (var i = 0; i < Math.min(n, 64); i++) {
        var e = off + 2 + i * 12;
        if (e + 12 > tiff.length) break;
        var tag = view.getUint16(e, little);
        if (tag === 0x0112) {
          var v = view.getUint16(e + 8, little);
          return (v >= 1 && v <= 8) ? v : 1;
        }
      }
    } catch (e) {}
    return 1;
  }
  function minimalApp1(orientation) {
    if (orientation < 2 || orientation > 8) return null;
    var tiff = new Uint8Array(26);
    tiff.set([0x49, 0x49, 0x2A, 0x00, 0x08, 0x00, 0x00, 0x00]);
    tiff[8] = 1; tiff[9] = 0;
    tiff[10] = 0x12; tiff[11] = 0x01; tiff[12] = 3; tiff[13] = 0; tiff[14] = 1; tiff[15] = 0; tiff[16] = 0; tiff[17] = 0;
    tiff[18] = orientation & 0xFF; tiff[19] = (orientation >> 8) & 0xFF;
    tiff[20] = 0; tiff[21] = 0; tiff[22] = 0; tiff[23] = 0; tiff[24] = 0; tiff[25] = 0;
    var payload = new Uint8Array(6 + tiff.length);
    payload.set([0x45, 0x78, 0x69, 0x66, 0x00, 0x00]); payload.set(tiff, 6);
    var seg = new Uint8Array(4 + payload.length);
    seg[0] = 0xFF; seg[1] = 0xE1;
    seg[2] = ((payload.length + 2) >> 8) & 0xFF; seg[3] = (payload.length + 2) & 0xFF;
    seg.set(payload, 4);
    return seg;
  }
  function stripJpeg(data) {
    if (data.length < 4 || data[0] !== 0xFF || data[1] !== 0xD8) return null;
    var orient = 1;
    var segs = jpegSegments(data);
    if (segs) {
      for (var s = 0; s < segs.length; s++) {
        if (segs[s].marker === 0xE1 && segs[s].data.length > 6 &&
            segs[s].data[0] === 0x45 && segs[s].data[1] === 0x78 && segs[s].data[2] === 0x69 && segs[s].data[3] === 0x66) {
          orient = tiffOrientation(segs[s].data.subarray(6));
          break;
        }
      }
    }
    var parts = [data.subarray(0, 2)], removed = [];
    var o1 = minimalApp1(orient);
    if (o1) parts.push(o1);
    var i = 2;
    while (i + 4 <= data.length) {
      if (data[i] !== 0xFF) break;
      var m = data[i + 1];
      if (m === 0xD8 || (m >= 0xD0 && m <= 0xD7)) { parts.push(data.subarray(i, i + 2)); i += 2; continue; }
      var len = (data[i + 2] << 8) | data[i + 3];
      if (i + 2 + len > data.length) break;
      if (m === 0xDA) { parts.push(data.subarray(i)); i = data.length; break; }
      if (m >= 0xE0 && m <= 0xEF) removed.push('APP' + (m - 0xE0));
      else if (m === 0xFE) removed.push('COM');
      else parts.push(data.subarray(i, i + 2 + len));
      i += 2 + len;
    }
    var out = concat(parts);
    if (out.length < 2 || out[out.length - 1] !== 0xD9 || out[out.length - 2] !== 0xFF) {
      var tail = new Uint8Array(2); tail[0] = 0xFF; tail[1] = 0xD9;
      parts.push(tail); out = concat(parts);
    }
    return { data: out, removed: uniq(removed) };
  }

  // ---- WebP ----
  function webpChunks(data) {
    if (data.length < 12 || data[0] !== 0x52 || data[1] !== 0x49 || data[2] !== 0x46 || data[3] !== 0x46) return null;
    if (data[8] !== 0x57 || data[9] !== 0x45 || data[10] !== 0x42 || data[11] !== 0x50) return null;
    var chunks = [], i = 12, view = new DataView(data.buffer, data.byteOffset, data.byteLength);
    while (i + 8 <= data.length) {
      var four = latin1(data.subarray(i, i + 4));
      var len = view.getUint32(i + 4, true);
      var end = i + 8 + len + (len & 1);
      if (end > data.length) break;
      chunks.push({ four: four, data: data.subarray(i + 8, i + 8 + len) });
      i = end;
    }
    return chunks;
  }
  function stripWebp(data) {
    var chunks = webpChunks(data);
    if (!chunks) return null;
    var drop = ['EXIF', 'XMP ', 'ICCP'];
    var flags = { ICCP: 0x20, EXIF: 0x08, 'XMP ': 0x04 };
    var removed = [];
    var parts = [data.subarray(0, 12)];
    var vp8xAt = -1;
    for (var i = 0; i < chunks.length; i++) {
      var ch = chunks[i];
      if (drop.indexOf(ch.four) >= 0) { removed.push(ch.four); continue; }
      if (ch.four === 'VP8X') vp8xAt = parts.length;
      var head = new Uint8Array(8);
      head[0] = ch.four.charCodeAt(0); head[1] = ch.four.charCodeAt(1);
      head[2] = ch.four.charCodeAt(2); head[3] = ch.four.charCodeAt(3);
      new DataView(head.buffer).setUint32(4, ch.data.length, true);
      parts.push(head, ch.data);
      if (ch.data.length & 1) parts.push(new Uint8Array(1));
    }
    var out = concat(parts);
    if (vp8xAt >= 0 && removed.length) {
      // 清除 VP8X 里被摘除块的标志位(vp8xAt 为 head 段位置, flags 字节在其后 8 字节)
      var fpos = 0;
      for (var p = 0; p < parts.length; p++) { if (p === vp8xAt) break; fpos += parts[p].length; }
      var fp = fpos + 8;
      if (out.length > fp) {
        var f = out[fp];
        for (var d = 0; d < removed.length; d++) f &= ~(flags[removed[d]] || 0);
        out[fp] = f & 0xFF;
      }
    }
    new DataView(out.buffer, out.byteOffset, 4).setUint32(0, out.length - 8, true);
    return { data: out, removed: uniq(removed) };
  }

  // ---- SVG ----
  function stripSvg(data) {
    var text = utf8(data);
    var removed = [];
    var n1 = (text.match(/<!--[\s\S]*?-->/g) || []).length;
    text = text.replace(/<!--[\s\S]*?-->/g, '');
    if (n1) removed.push('XML注释x' + n1);
    var n2 = (text.match(/<metadata(?:\s[^>]*)?>[\s\S]*?<\/metadata>/g) || []).length;
    text = text.replace(/<metadata(?:\s[^>]*)?>[\s\S]*?<\/metadata>/g, '');
    if (n2) removed.push('metadata块x' + n2);
    var n3 = (text.match(/\s(?:\w+:)?generator="[^"]*"/g) || []).length;
    text = text.replace(/\s(?:\w+:)?generator="[^"]*"/g, '');
    if (n3) removed.push('generator属性x' + n3);
    var n4 = (text.match(/\s(?:dc:)?creator="[^"]*"/g) || []).length;
    text = text.replace(/\s(?:dc:)?creator="[^"]*"/g, '');
    if (n4) removed.push('creator属性x' + n4);
    return { data: new TextEncoder().encode(text), removed: removed };
  }

  // ---- 扫描 ----
  function scanXmp(text, out) {
    if (!text || text.length < 5) return;
    var low = text.toLowerCase();
    if (low.indexOf('trainedalgorithmicmedia') >= 0 || low.indexOf('digitalsourcetype') >= 0 ||
        low.indexOf('claim_generator') >= 0 || low.indexOf('c2pa') >= 0) {
      out.findings.push({ key: 'XMP', value: 'xmp_ai_decl', kind: 'ai_flag' });
    }
    for (var a = 0; a < XMP_ATTRS.length; a++) {
      var attr = XMP_ATTRS[a];
      var re = new RegExp('<' + attr.replace(/:/g, ':') + '(?:\\s[^>]*)?>([^<]{0,300})<\\/', 'gi');
      var m;
      while ((m = re.exec(text)) !== null) {
        var val = m[1].trim();
        if (!val) continue;
        out.metadata.push({ name: attr, value: trunc(val, 200) });
        var c = classify(attr + ' ' + val);
        if (c) out.findings.push({ key: 'XMP:' + attr, value: val, kind: c.kind });
      }
    }
    var are = /(\w+:\w+)="([^"]{1,300})"/g, am;
    while ((am = are.exec(text)) !== null) {
      var a2 = am[1], v2 = am[2];
      var keyLow = (a2 + ' ' + v2).toLowerCase();
      if (XMP_ATTRS.indexOf(a2.toLowerCase()) >= 0 ||
          keyLow.indexOf('creator') >= 0 || keyLow.indexOf('c2pa') >= 0 ||
          keyLow.indexOf('digitalsource') >= 0 || keyLow.indexOf('aigc') >= 0 ||
          keyLow.indexOf('generated') >= 0) {
        out.metadata.push({ name: a2, value: trunc(v2, 200) });
        var c2 = classify(a2 + ' ' + v2);
        if (c2) out.findings.push({ key: 'XMP:' + a2, value: v2, kind: c2.kind });
      }
    }
  }

  var EXIF_TAGS = {
    0x010F: 'Make', 0x0110: 'Model', 0x0131: 'Software', 0x0132: 'DateTime',
    0x9003: 'DateTimeOriginal', 0x9004: 'DateTimeDigitized', 0x0112: 'Orientation',
    0x010E: 'ImageDescription', 0x013B: 'Artist', 0x9286: 'UserComment',
    0xA431: 'BodySerialNumber', 0xA434: 'LensModel', 0xA435: 'LensSerialNumber',
    0xA420: 'ImageUniqueID', 0xA433: 'LensMake', 0x829A: 'ExposureTime',
    0x829D: 'FNumber', 0x8827: 'ISOSpeedRatings', 0x920A: 'FocalLength',
  };
  function parseTiff(tiff, out) {
    try {
      if (tiff.length < 10) return;
      var little = tiff[0] === 0x49 && tiff[1] === 0x49;
      if (!little && !(tiff[0] === 0x4D && tiff[1] === 0x4D)) return;
      var view = new DataView(tiff.buffer, tiff.byteOffset, tiff.byteLength);
      var off = view.getUint32(4, little);
      var n = view.getUint16(off, little);
      var hasGps = false;
      for (var i = 0; i < Math.min(n, 80); i++) {
        var e = off + 2 + i * 12;
        if (e + 12 > tiff.length) break;
        var tag = view.getUint16(e, little);
        var type = view.getUint16(e + 2, little);
        var count = view.getUint32(e + 4, little);
        if (tag === 0x8825) { hasGps = true; continue; }
        var name = EXIF_TAGS[tag];
        if (!name) continue;
        var val = '';
        if (type === 2) {
          var len = Math.min(count, tiff.length - (e + 8));
          val = latin1(tiff.subarray(e + 8, e + 8 + len)).replace(/\0+$/, '').trim();
        } else if (type === 3) {
          val = String(count === 1 ? view.getUint16(e + 8, little) : view.getUint16(e + 8, little));
        } else if (type === 4) {
          val = String(count === 1 ? view.getUint32(e + 8, little) : view.getUint32(e + 8, little));
        } else if (type === 5 && count >= 1) {
          var num = view.getUint32(e + 8, little), den = view.getUint32(e + 12, little);
          val = den ? String(Math.round(num / den * 1000) / 1000) : String(num);
        } else {
          continue;
        }
        if (!val) continue;
        out.metadata.push({ name: name, value: trunc(val, 120) });
        var c = classify(name + ' ' + val);
        if (c) out.findings.push({ key: 'EXIF:' + name, value: val, kind: c.kind });
      }
      if (hasGps) out.metadata.push({ name: 'GPSInfo', value: 'gps_present' });
    } catch (e) {}
  }
  function scanImage(data, ext) {
    var out = { verdict: 'clean', findings: [], metadata: [], c2pa: false, width: 0, height: 0 };
    // C2PA 字节扫描
    for (var i = 0; i < C2PA_MARKERS.length; i++) {
      if (indexOfBytes(data, C2PA_MARKERS[i]) >= 0) {
        out.c2pa = true;
        out.findings.push({ key: 'byte_stream', value: 'found_marker', kind: 'c2pa', arg: C2PA_MARKERS[i] });
        break;
      }
    }
    if (ext === 'png') {
      var chunks = pngChunks(data) || [];
      for (var p = 0; p < chunks.length; p++) {
        var ch = chunks[p];
        if (ch.type === 'IHDR' && ch.data.length >= 8) {
          var dv = new DataView(ch.data.buffer, ch.data.byteOffset, ch.data.byteLength);
          out.width = dv.getUint32(0, false); out.height = dv.getUint32(4, false);
        }
        if (ch.type === 'tEXt' || ch.type === 'zTXt' || ch.type === 'iTXt') {
          var kv = parsePngText(ch.type, ch.data);
          out.metadata.push({ name: ch.type + ':' + kv[0], value: trunc(kv[1], 200) });
          var c = classify(kv[0] + ' ' + kv[1]);
          if (c) out.findings.push({ key: ch.type + ':' + kv[0], value: trunc(kv[1], 200), kind: c.kind });
        } else if (ch.type === 'eXIf') {
          out.metadata.push({ name: 'eXIf', value: 'exif_present' });
          parseTiff(ch.data, out);
        } else if (ch.type === 'caBX' || ch.type === 'C2PA') {
          out.c2pa = true;
          out.findings.push({ key: ch.type, value: 'c2pa_chunk', kind: 'c2pa' });
        } else if (ch.type === 'tIME') {
          out.metadata.push({ name: 'tIME', value: 'last_modified' });
        }
      }
    } else if (ext === 'jpg' || ext === 'jpeg') {
      var segs = jpegSegments(data) || [];
      for (var s = 0; s < segs.length; s++) {
        var sg = segs[s];
        if (sg.marker >= 0xE0 && sg.marker <= 0xEF) {
          if (sg.marker === 0xE0) continue;
          var label = { 0xE1: 'APP1', 0xE2: 'APP2', 0xED: 'APP13', 0xE7: 'APP11' }[sg.marker] || ('APP' + (sg.marker - 0xE0));
          out.metadata.push({ name: label, value: sg.data.length + ' B' });
          if (sg.marker === 0xE1 && sg.data.length > 29) {
            var head = latin1(sg.data.subarray(0, 29));
            if (head.indexOf('http://ns.adobe.com/xap/') === 0) scanXmp(utf8(sg.data.subarray(29)), out);
            else if (sg.data[0] === 0x45 && sg.data[1] === 0x78 && sg.data[2] === 0x69 && sg.data[3] === 0x66) parseTiff(sg.data.subarray(6), out);
          }
          if (sg.marker === 0xE7 && sg.data.length > 2 && sg.data[0] === 0x4A && sg.data[1] === 0x50) {
            if (indexOfBytes(sg.data, 'c2pa') >= 0) {
              out.c2pa = true;
              out.findings.push({ key: label, value: 'jumbf_c2pa', kind: 'c2pa' });
            }
          }
          var runs = findRuns(sg.data, 5);
          for (var rr = 0; rr < runs.length; rr++) {
            var c3 = classify(runs[rr]);
            if (c3) out.findings.push({ key: label, value: trunc(runs[rr], 120), kind: c3.kind });
          }
        } else if (sg.marker === 0xFE) {
          var txt = utf8(sg.data);
          out.metadata.push({ name: 'COM', value: trunc(txt, 160) });
          var c4 = classify(txt);
          if (c4) out.findings.push({ key: 'COM', value: trunc(txt, 160), kind: c4.kind });
        }
      }
    } else if (ext === 'webp') {
      var wch = webpChunks(data) || [];
      for (var w = 0; w < wch.length; w++) {
        var wc = wch[w];
        if (wc.four === 'EXIF') {
          out.metadata.push({ name: 'WebP:EXIF', value: wc.data.length + ' B' });
          if (wc.data.length >= 6) parseTiff(wc.data, out);
          var runs2 = findRuns(wc.data, 5);
          for (var r2 = 0; r2 < runs2.length; r2++) {
            var c5 = classify(runs2[r2]);
            if (c5) out.findings.push({ key: 'WebP:EXIF', value: trunc(runs2[r2], 120), kind: c5.kind });
          }
        } else if (wc.four === 'XMP ') {
          scanXmp(utf8(wc.data), out);
        }
      }
    } else if (ext === 'svg') {
      var text = utf8(data);
      var wm = text.match(/<svg[^>]*\swidth="([\d.]+)"/), hm = text.match(/<svg[^>]*\sheight="([\d.]+)"/);
      if (wm && hm) { out.width = parseInt(wm[1], 10) || 0; out.height = parseInt(hm[1], 10) || 0; }
      var cm, cre = /<!--([\s\S]*?)-->/g;
      while ((cm = cre.exec(text)) !== null) {
        var comment = cm[1].trim();
        if (!comment) continue;
        out.metadata.push({ name: 'svg_comment', value: trunc(comment, 160) });
        var c6 = classify(comment);
        if (c6) out.findings.push({ key: 'svg_comment', value: trunc(comment, 160), kind: c6.kind });
      }
      var gm, gre = /(\w+:)?generator="([^"]+)"/gi;
      while ((gm = gre.exec(text)) !== null) {
        out.metadata.push({ name: 'svg_generator', value: trunc(gm[2], 120) });
        var c7 = classify(gm[2]);
        if (c7) out.findings.push({ key: 'svg_generator', value: trunc(gm[2], 120), kind: c7.kind });
      }
      var mm, mre = /<metadata(?:\s[^>]*)?>([\s\S]*?)<\/metadata>/g;
      while ((mm = mre.exec(text)) !== null) {
        var inner = mm[1].replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim();
        if (inner) {
          out.metadata.push({ name: 'svg_meta', value: trunc(inner, 160) });
          var c8 = classify(inner);
          if (c8) out.findings.push({ key: 'svg_meta', value: trunc(inner, 160), kind: c8.kind });
        }
      }
    }
    // 裁决
    var kinds = {};
    for (var f = 0; f < out.findings.length; f++) kinds[out.findings[f].kind] = 1;
    if (out.c2pa || kinds.ai) out.verdict = 'high';
    else if (kinds.ai_flag) out.verdict = 'medium';
    else if (out.metadata.length || kinds.app || kinds.metadata) out.verdict = 'low';
    return out;
  }
  function stripImage(data, ext) {
    if (ext === 'png') return stripPng(data);
    if (ext === 'jpg' || ext === 'jpeg') return stripJpeg(data);
    if (ext === 'webp') return stripWebp(data);
    if (ext === 'svg') return stripSvg(data);
    return null;
  }

  function indexOfBytes(haystack, needle) {
    var nl = needle.length;
    if (!nl || haystack.length < nl) return -1;
    for (var i = 0; i <= haystack.length - nl; i++) {
      var ok = true;
      for (var j = 0; j < nl; j++) if (haystack[i + j] !== needle.charCodeAt(j)) { ok = false; break; }
      if (ok) return i;
    }
    return -1;
  }
  function concat(parts) {
    var total = 0;
    for (var i = 0; i < parts.length; i++) total += parts[i].length;
    var out = new Uint8Array(total), off = 0;
    for (var j = 0; j < parts.length; j++) { out.set(parts[j], off); off += parts[j].length; }
    return out;
  }
  function uniq(arr) {
    var seen = {}, out = [];
    for (var i = 0; i < arr.length; i++) if (!seen[arr[i]]) { seen[arr[i]] = 1; out.push(arr[i]); }
    return out;
  }

  var Engine = {
    pngChunks: pngChunks, jpegSegments: jpegSegments, webpChunks: webpChunks,
    stripPng: stripPng, stripJpeg: stripJpeg, stripWebp: stripWebp, stripSvg: stripSvg,
    stripImage: stripImage, scanImage: scanImage, classify: classify,
    crc32: crc32, utf8: utf8, latin1: latin1, parseTiff: parseTiff,
  };
  root.MRPEngine = Engine;
  if (typeof module !== 'undefined' && module.exports) module.exports = Engine;
})(typeof globalThis !== 'undefined' ? globalThis : this);
