/* ============================================================
 * Metadata Remove Pro Web - Video container metadata strip & scan
 * (MP4/MOV ISOBMFF · MKV/WebM EBML · AVI RIFF)
 * Pure-JS, offset-preserving: metadata regions are zeroed in place
 * (ISO box -> 'free', EBML element -> Void, RIFF LIST -> 'JUNK'),
 * so stco/co64 chunk offsets and frame data stay byte-identical.
 * No transcode. No dependencies. Node & browser compatible.
 * Copyright (c) 2026. All rights reserved.
 * ============================================================ */
(function (root) {
  'use strict';

  var TD = (typeof TextDecoder !== 'undefined') ? new TextDecoder('utf-8', { fatal: false }) : null;
  function utf8(b, o, n) {
    if (TD) { try { return TD.decode(b.subarray(o, o + n)); } catch (e) {} }
    var s = ''; for (var i = o; i < o + n; i++) s += String.fromCharCode(b[i]); return s;
  }
  function latin1(b, o, n) {
    var s = ''; for (var i = o; i < o + n; i++) s += String.fromCharCode(b[i]); return s;
  }
  function fourcc(b, o) { return latin1(b, o, 4); }
  function u32(b, o) { return ((b[o] << 24) | (b[o + 1] << 16) | (b[o + 2] << 8) | b[o + 3]) >>> 0; }
  function u16(b, o) { return (b[o] << 8) | b[o + 1]; }
  function trunc(s, n) {
    s = String(s == null ? '' : s).replace(/\s+/g, ' ').trim();
    return s.length > n ? s.slice(0, n) + '…' : s;
  }
  function indexOfBytes(haystack, needle) {
    var nl = needle.length;
    if (!nl || haystack.length < nl) return -1;
    outer: for (var i = 0; i <= haystack.length - nl; i++) {
      for (var j = 0; j < nl; j++) if (haystack[i + j] !== needle.charCodeAt(j)) continue outer;
      return i;
    }
    return -1;
  }
  function findRuns(b, o, n, minLen) {
    var runs = [], cur = [], end = Math.min(o + n, b.length);
    for (var i = o; i < end; i++) {
      var c = b[i];
      if (c >= 32 && c < 127) cur.push(c);
      else { if (cur.length >= minLen) runs.push(latin1(cur, 0, cur.length)); cur = []; }
    }
    if (cur.length >= minLen) runs.push(latin1(cur, 0, cur.length));
    return runs;
  }
  function classify(text) {
    if (root.MRPEngine && typeof root.MRPEngine.classify === 'function') {
      var c = root.MRPEngine.classify(text);
      if (c) return c;
    }
    var low = String(text || '').toLowerCase();
    var AI = ['midjourney', 'dall-e', 'dalle', 'chatgpt', 'openai', 'stable diffusion', 'stabilityai',
      'comfyui', 'automatic1111', 'a1111', 'novelai', 'leonardo', 'ideogram', 'firefly', 'imagen',
      'gemini', 'sora', 'veo', 'runway', 'gen-3', 'gen3', 'pika', 'kling', 'hailuo', 'jimeng',
      'vidu', 'luma', 'flux', 'negative prompt', 'cfg scale', 'checkpoint', 'loras'];
    for (var i = 0; i < AI.length; i++) if (low.indexOf(AI[i]) >= 0) return { kind: 'ai', sig: AI[i] };
    var FL = ['aigc', 'ai-generated', 'ai generated', 'generated by ai', 'generated with ai', 'made with ai', 'created with ai', 'digitalsourcetype', 'claim_generator', 'trainedalgorithmicmedia'];
    for (var j = 0; j < FL.length; j++) if (low.indexOf(FL[j]) >= 0) return { kind: 'ai_flag', sig: FL[j] };
    var APP = ['capcut', 'jianying', 'canva', 'photoshop', 'adobe', 'tiktok', 'douyin', 'instagram', 'after effects', 'premiere', 'final cut'];
    for (var k = 0; k < APP.length; k++) if (low.indexOf(APP[k]) >= 0) return { kind: 'app', sig: APP[k] };
    return null;
  }
  function verdictOf(out) {
    var kinds = {};
    for (var f = 0; f < out.findings.length; f++) kinds[out.findings[f].kind] = 1;
    if (out.c2pa || kinds.ai) return 'high';
    if (kinds.ai_flag) return 'medium';
    if (out.metadata.length || kinds.app || kinds.metadata) return 'low';
    return 'clean';
  }
  function scanC2pa(data, out) {
    if (!data || !data.length) return;
    var limit = Math.min(data.length, 64 * 1024 * 1024);
    var m = ['c2pa', 'jumd', 'JUMBF'];
    for (var i = 0; i < m.length; i++) {
      if (indexOfBytes(data.subarray(0, limit), m[i]) >= 0) {
        out.c2pa = true;
        out.findings.push({ key: 'byte_stream', value: 'found_marker', kind: 'c2pa', arg: m[i] });
        return;
      }
    }
  }

  /* ================= ISOBMFF (MP4 / MOV / M4V) ================= */
  var ISO_CONTAINERS = {
    moov: 1, trak: 1, mdia: 1, minf: 1, stbl: 1, dinf: 1, edts: 1, udta: 1, meta: 1, ilst: 1,
    '----': 1, moof: 1, traf: 1, mvex: 1, tref: 1, sinf: 1, schi: 1, iprp: 1, ipco: 1, iinf: 1, strk: 1, strd: 1,
  };
  // iTunes ilst item 4cc -> human name
  var ILST_NAMES = {
    '©nam': 'mp4_title', '©ART': 'mp4_artist', '©cmt': 'mp4_comment', '©too': 'mp4_encoder',
    '©cpy': 'mp4_copyright', '©day': 'mp4_date', '©alb': 'mp4_album', '©gen': 'mp4_genre',
    '©wrt': 'mp4_writer', 'auth': 'mp4_author', 'desc': 'mp4_description', 'titl': 'mp4_title',
    'cprt': 'mp4_copyright', 'covr': 'mp4_cover', 'ldes': 'mp4_description', 'purd': 'mp4_purchase',
    '©lyr': 'mp4_lyrics', '©grp': 'mp4_grouping', 'gnre': 'mp4_genre', '©swr': 'mp4_encoder',
  };
  function isoWalk(data, cb) {
    // cb(type, pos, size, hdrLen, path) ; return false to skip children
    var view = new DataView(data.buffer, data.byteOffset, data.byteLength);
    var n = data.length;
    var path = [];
    (function walk(start, end) {
      var pos = start;
      while (pos + 8 <= end) {
        var size = view.getUint32(pos, false);
        var hdr = 8;
        if (size === 1) {
          if (pos + 16 > end) break;
          try { size = Number(view.getBigUint64(pos + 8, false)); } catch (e) { break; }
          hdr = 16;
        } else if (size === 0) {
          size = end - pos;
        }
        if (size < hdr || pos + size > end) break;
        var type = fourcc(data, pos + 4);
        var go = cb(type, pos, size, hdr, path);
        if (go !== false && ISO_CONTAINERS[type]) {
          path.push(type);
          // meta 为 FullBox(+4 v/f); iinf 为 FullBox + 2 字节 entry_count
          var childOff = (type === 'meta') ? 4 : (type === 'iinf') ? 6 : 0;
          walk(pos + hdr + childOff, pos + size);
          path.pop();
        }
        pos += size;
      }
    })(0, n);
  }
  function isoStrip(data) {
    var regions = [], removed = [];
    isoWalk(data, function (type, pos, size, hdr) {
      if (type === 'udta' || type === 'meta') {
        regions.push([pos, size]);
        removed.push('MP4:' + type);
        return false; // 整盒零化, 无需深入
      }
      // 含 C2PA 标记的 uuid 盒(规范要求可安全忽略)一并零化
      if (type === 'uuid' && size - hdr >= 4 &&
          (indexOfBytes(data.subarray(pos + hdr, pos + size), 'c2pa') >= 0 ||
           indexOfBytes(data.subarray(pos + hdr, pos + size), 'jumd') >= 0)) {
        regions.push([pos, size]);
        removed.push('MP4:uuid(c2pa)');
        return false;
      }
      return true;
    });
    if (!regions.length) return { data: null, removed: [] };
    var out = new Uint8Array(data.length);
    out.set(data);
    for (var r = 0; r < regions.length; r++) {
      var p = regions[r][0], sz = regions[r][1];
      out[p] = 0x66; out[p + 1] = 0x72; out[p + 2] = 0x65; out[p + 3] = 0x65; // 'free'
      for (var i = p + 4; i < p + sz; i++) out[i] = 0;
    }
    var uniq = {};
    var rem = [];
    for (var u = 0; u < removed.length; u++) if (!uniq[removed[u]]) { uniq[removed[u]] = 1; rem.push(removed[u]); }
    return { data: out, removed: rem };
  }
  function parseDataBox(data, p, sz) {
    // ilst 'data' 子盒存在两种真实布局:
    // A(ffmpeg): type(4) + locale(4) + value        -> value 在 p+16
    // B(Apple):  v/f(4) + type(4) + locale(4) + value -> value 在 p+20
    var a0 = u32(data, p + 8), a1 = u32(data, p + 12);
    var dtyp = 0, off = p + 16, len = sz - 16;
    if ((a0 === 1 || a0 === 13 || a0 === 14 || a0 === 21 || a0 === 27) && a1 === 0) {
      dtyp = a0;
    } else if (a0 === 0 && (a1 === 1 || a1 === 13 || a1 === 14 || a1 === 21 || a1 === 27)) {
      dtyp = a1; off = p + 20; len = sz - 20;
    } else {
      dtyp = a0;
    }
    if (len < 0) len = 0;
    var text = '';
    if (dtyp === 1) text = utf8(data, off, Math.min(len, 2048));
    return { dtyp: dtyp, text: text };
  }
  function isoScan(data, out) {
    out.kind = 'isobmff';
    var view = new DataView(data.buffer, data.byteOffset, data.byteLength);
    var keys = [];
    isoWalk(data, function (type, pos, size, hdr, path) {
      var depth = path.length;
      // 尺寸与时长
      if (type === 'mvhd' && size >= hdr + 20) {
        var ver = data[pos + hdr];
        // v0: v/f(4) ctime(4) mtime(4) timescale(4) duration(4) ...
        // v1: v/f(4) ctime(8) mtime(8) timescale(4) duration(8) ...
        if (ver === 1 && size >= hdr + 32) {
          var ts = view.getUint32(pos + hdr + 20, false), dur = Number(view.getBigUint64(pos + hdr + 24, false));
        } else if (size >= hdr + 20) {
          var ts = view.getUint32(pos + hdr + 12, false), dur = view.getUint32(pos + hdr + 16, false);
        }
        if (ts && !out.duration) out.duration = Math.round(dur / ts * 100) / 100;
        return false;
      }
      if (type === 'tkhd' && size >= hdr + 84) {
        var ver1 = data[pos + hdr];
        var wOff = (ver1 === 1) ? hdr + 88 : hdr + 76;
        if (size >= wOff + 8) {
          var w = view.getUint32(pos + wOff, false) / 65536;
          var h2 = view.getUint32(pos + wOff + 4, false) / 65536;
          out.width = Math.max(out.width || 0, w | 0);
          out.height = Math.max(out.height || 0, h2 | 0);
        }
        return false;
      }
      // keys box(QuickTime metadata keys)
      if (type === 'keys' && path[path.length - 1] === 'meta') {
        try {
          var cnt = u32(data, pos + hdr + 4), off = pos + hdr + 8;
          for (var i = 0; i < Math.min(cnt, 64); i++) {
            if (off + 8 > pos + size) break;
            var klen = u32(data, off);
            // 条目 = size(4) + namespace(4, 'mdta') + value(klen-8), 即整条 klen 字节
            if (off + klen > pos + size) break;
            keys.push(utf8(data, off + 8, klen - 8));
            off += klen;
          }
        } catch (e) {}
        return false;
      }
      // ilst 条目
      if (depth >= 1 && path[depth - 1] === 'ilst' && size >= hdr) {
        var name = ILST_NAMES[type];
        var isCustom = (type === '----');
        var isCprt = (type === 'cprt');
        if (name || isCustom) {
          var text = '';
          var binary = false;
          if (isCprt) {
            if (size >= hdr + 6) text = utf8(data, pos + hdr + 6, size - hdr - 6);
          } else if (isCustom) {
            var mean = '', nm = '';
            // 子盒 mean/name/data
            var p2 = pos + hdr, end2 = pos + size;
            while (p2 + 8 <= end2) {
              var sz2 = u32(data, p2), t2 = fourcc(data, p2 + 4);
              if (sz2 < 8 || p2 + sz2 > end2) break;
              if (t2 === 'mean' && sz2 >= 16) mean = utf8(data, p2 + 12, sz2 - 12).replace(/\0+$/, '');
              else if (t2 === 'name' && sz2 >= 16) nm = utf8(data, p2 + 12, sz2 - 12).replace(/\0+$/, '');
              else if (t2 === 'data' && sz2 >= 16) {
                var db = parseDataBox(data, p2, sz2);
                if (db.dtyp === 1) text = db.text;
                else binary = true;
              }
              p2 += sz2;
            }
            name = 'mp4_custom';
            if (mean) keys.unshift(mean + (nm ? '/' + nm : ''));
            if (!text && !binary && mean) text = 'mp4_custom_present';
          } else {
            var p3 = pos + hdr, end3 = pos + size;
            while (p3 + 8 <= end3) {
              var sz3 = u32(data, p3), t3 = fourcc(data, p3 + 4);
              if (sz3 < 8 || p3 + sz3 > end3) break;
              if (t3 === 'data' && sz3 >= 16) {
                var db3 = parseDataBox(data, p3, sz3);
                if (db3.dtyp === 1) text = db3.text;
                else if (db3.dtyp === 13 || db3.dtyp === 14) { binary = true; }
              }
              p3 += sz3;
            }
          }
          if (binary && !text) {
            out.metadata.push({ name: name === 'mp4_custom' ? 'mp4_cover' : name, value: 'binary_data' });
            return true;
          }
          text = trunc(text, 200);
          if (text) {
            out.metadata.push({ name: name, value: text });
            var c = classify(text);
            if (c) out.findings.push({ key: 'MP4:' + type, value: text, kind: c.kind });
          }
        }
        return true;
      }
      // meta/udta 内的其他子盒: uuid(XMP 等)按字符串扫
      if ((depth >= 2 && path[depth - 1] === 'meta' && path[depth - 2] !== 'ilst') ||
          (depth >= 1 && path[depth - 1] === 'udta')) {
        if (type === 'uuid' || type === 'XMP ') {
          var runs = findRuns(data, pos + hdr, size - hdr, 6);
          for (var rr = 0; rr < runs.length; rr++) {
            var c2 = classify(runs[rr]);
            if (c2) out.findings.push({ key: 'MP4:' + type, value: trunc(runs[rr], 120), kind: c2.kind });
          }
        }
        if (type === 'hdlr' && size >= hdr + 12) {
          var hd = latin1(data, pos + hdr + 8, 4);
          if (hd === 'mdir' || hd === 'mdta') out.metadata.push({ name: 'mp4_mdta_handler', value: 'mdta' });
        }
      }
      return true;
    });
    if (keys.length) out.metadata.push({ name: 'mp4_keys', value: trunc(keys.join(' | '), 200) });
  }

  /* ================= EBML (MKV / WebM) ================= */
  function vint(b, o, maxLen) {
    if (o >= b.length) return null;
    var first = b[o];
    if (first === 0) return null;
    var mask = 0x80, len = 1;
    while (len <= (maxLen || 8) && !(first & mask)) { mask >>= 1; len++; }
    if (len > (maxLen || 8)) return null;
    var value = first & (mask - 1);
    for (var i = 1; i < len; i++) {
      if (o + i >= b.length) return null;
      value = value * 256 + b[o + i];
    }
    // canon: 还原标准 matroska 元素 ID 写法(首字节含长度标记), 便于与 0x18538067 等常量比较
    var canon = value + ((0x80 << (7 * (len - 1))) >>> 0);
    return { value: value, len: len, canon: canon };
  }
  var EBML_ELEMS = {
    0x1A45DFA3: 'EBML', 0x18538067: 'Segment', 0x114D9B74: 'SeekHead', 0x1549A966: 'Info',
    0x1654AE6B: 'Tracks', 0xAE: 'TrackEntry', 0xE0: 'Video', 0x1254C367: 'Tags', 0x7373: 'Tag',
    0x67C8: 'SimpleTag', 0x1941A469: 'Attachments', 0x61A7: 'AttachedFile', 0x1F43B675: 'Cluster',
    0x2AD7B1: 'TimestampScale', 0x4489: 'Duration', 0x7BA9: 'Title', 0x4461: 'DateUTC',
    0x45A3: 'TagName', 0x4487: 'TagString', 0x4485: 'TagBinary', 0xB0: 'PixelWidth', 0xBA: 'PixelHeight',
    0x4D80: 'MuxingApp', 0x5741: 'WritingApp', 0x73C5: 'TagLanguage', 0x63C0: 'Chapters', 0x5034435: 'ContentEncodings',
  };
  var EBML_CONTAINERS = {
    0x1A45DFA3: 1, 0x18538067: 1, 0x114D9B74: 1, 0x1549A966: 1, 0x1654AE6B: 1, 0xAE: 1, 0xE0: 1,
    0x1254C367: 1, 0x7373: 1, 0x67C8: 1, 0x1941A469: 1, 0x61A7: 1, 0x63C0: 1,
  };
  function ebmlWalk(data, start, end, depth, cb) {
    var pos = start;
    while (pos < end) {
      var id = vint(data, pos, 4);
      if (!id) return;
      var sp = vint(data, pos + id.len, 8);
      if (!sp) return;
      var size = sp.value, sizeLen = sp.len, unknown = false;
      if (size === 0xFFFFFFFFFFFFFFFFFF || size === 0x7FFFFFFFFFFFFFFF || size === (Math.pow(2, 7 * sizeLen) - 1)) {
        // 未知大小(全 1): 按到末尾处理(仅 Segment/Cluster 合法)
        size = end - pos - id.len - sizeLen; unknown = true;
      }
      var total = id.len + sizeLen + size;
      if (pos + total > end) return;
      var stop = cb(id.canon, pos, total, id.len, sizeLen, size, depth, unknown);
      if (stop !== false && EBML_CONTAINERS[id.canon]) ebmlWalk(data, pos + id.len + sizeLen, pos + total, depth + 1, cb);
      pos += total;
    }
  }
  // 构造恰好占 totalLen 字节的 Void 元素头(0xEC + size + 全零负载)
  function voidHeader(totalLen) {
    if (totalLen < 2) return null;
    var sizeLen = 1, value = totalLen - 2;
    // vint size 长度随数值大小变化, 迭代收敛
    for (var i = 0; i < 4; i++) {
      var v2 = totalLen - 1 - sizeLen;
      var l2 = vintSize(v2);
      if (l2 === sizeLen) { value = v2; break; }
      sizeLen = l2; value = v2;
    }
    var head = new Uint8Array(1 + sizeLen);
    head[0] = 0xEC;
    var v = value;
    for (var j = sizeLen - 1; j >= 0; j--) { head[1 + j] = v & 0xFF; v = Math.floor(v / 256); }
    head[1] = head[1] | (0x80 >> (sizeLen - 1));
    return head;
  }
  function vintSize(value) {
    // 1 字节 vint 存 7 位, n 字节存 7n 位
    var len = 1;
    while (value > Math.pow(2, 7 * len) - 1) len++;
    return len;
  }
  function ebmlStrip(data) {
    var regions = [], removed = [];
    if (data.length < 4 || u32(data, 0) !== 0x1A45DFA3) return null;
    // 找到 Segment 起点
    var segStart = -1, segEnd = data.length;
    var pos = 0;
    while (pos + 2 <= data.length) {
      var hid = vint(data, pos, 4);
      if (!hid) break;
      var hsp = vint(data, pos + hid.len, 8);
      if (!hsp) break;
      if (hid.canon === 0x18538067) {
        segStart = pos;
        var sz = hsp.value;
        var allOnes = true;
        for (var q = 0; q < hsp.len; q++) if (data[pos + hid.len + q] !== 0xFF) { allOnes = false; break; }
        if (!allOnes && pos + hid.len + hsp.len + sz <= data.length) segEnd = pos + hid.len + hsp.len + sz;
        break;
      }
      var t2 = hid.len + hsp.len + hsp.value;
      if (t2 <= 0 || pos + t2 > data.length) break;
      pos += t2;
    }
    if (segStart < 0) return { data: null, removed: [] };
    ebmlWalk(data, segStart + 0, segEnd, 0, function (id, pos2, total, idLen, sizeLen, size) {
      if (id === 0x1254C367) { // Tags
        regions.push([pos2, total]);
        removed.push('MKV:Tags');
        return false;
      }
      if (id === 0x7BA9 || id === 0x4461) { // Info/Title, Info/DateUTC
        regions.push([pos2, total]);
        removed.push(id === 0x7BA9 ? 'MKV:Title' : 'MKV:DateUTC');
        return false;
      }
      if (id === 0x1941A469) { // Attachments(封面/附件)
        regions.push([pos2, total]);
        removed.push('MKV:Attachments');
        return false;
      }
      return true;
    });
    if (!regions.length) return { data: null, removed: [] };
    var out = new Uint8Array(data.length);
    out.set(data);
    var failed = 0;
    for (var r = 0; r < regions.length; r++) {
      var p = regions[r][0], total3 = regions[r][1];
      var head = voidHeader(total3);
      if (!head || head.length > total3) { failed++; continue; }
      out.set(head, p);
      for (var i2 = p + head.length; i2 < p + total3; i2++) out[i2] = 0;
    }
    var uniq = {}, rem = [];
    for (var u2 = 0; u2 < removed.length; u2++) if (!uniq[removed[u2]]) { uniq[removed[u2]] = 1; rem.push(removed[u2]); }
    return { data: (failed === regions.length) ? null : out, removed: rem };
  }
  function ebmlScan(data, out) {
    out.kind = 'ebml';
    if (data.length < 4 || u32(data, 0) !== 0x1A45DFA3) return;
    var ts = 1000000, durationNs = null;
    var tags = [];
    function readFloat(p, n) {
      if (n === 4) return new DataView(data.buffer, data.byteOffset + p, 4).getFloat32(0, false);
      if (n === 8) return new DataView(data.buffer, data.byteOffset + p, 8).getFloat64(0, false);
      return 0;
    }
    function readUint(p, n) {
      var v = 0;
      for (var i = 0; i < n && p + i < data.length; i++) v = v * 256 + data[p + i];
      return v;
    }
    ebmlWalk(data, 0, data.length, 0, function (id, pos2, total, idLen, sizeLen, size, depth) {
      var payload = pos2 + idLen + sizeLen;
      if (id === 0x2AD7B1 && size >= 1) { ts = readUint(payload, Math.min(size, 8)) || 1000000; return false; }
      if (id === 0x4489 && size >= 4) { durationNs = readFloat(payload, Math.min(size, 8)); return false; }
      if (id === 0x7BA9 && size >= 1) {
        var t = trunc(utf8(data, payload, size), 200);
        out.metadata.push({ name: 'mkv_title', value: t });
        var c = classify(t);
        if (c) out.findings.push({ key: 'MKV:Title', value: t, kind: c.kind });
        return false;
      }
      if (id === 0x4461 && size >= 8) {
        // Matroska DateUTC: 自 2001-01-01 起的纳秒(有符号)
        var neg = (data[payload] & 0x80) !== 0;
        var ns = 0;
        for (var i = 0; i < 8; i++) ns = ns * 256 + data[payload + i];
        if (neg) ns -= Math.pow(2, 64);
        var dt = new Date(978307200000 + Math.round(ns / 1000000));
        if (!isNaN(dt.getTime())) out.metadata.push({ name: 'mkv_creation_time', value: dt.toISOString().slice(0, 19).replace('T', ' ') });
        return false;
      }
      if (id === 0x45A3 && size >= 1) { tags.push('name:' + trunc(utf8(data, payload, size), 80)); return false; }
      if (id === 0x4487 && size >= 1) {
        var tv = trunc(utf8(data, payload, size), 200);
        out.metadata.push({ name: 'mkv_tag', value: tv });
        var c2 = classify(tv);
        if (c2) out.findings.push({ key: 'MKV:Tag', value: tv, kind: c2.kind });
        return false;
      }
      if (id === 0x4485 && size >= 1) { out.metadata.push({ name: 'mkv_tag_binary', value: size + ' B' }); return false; }
      if (id === 0x4D80 && size >= 1) {
        var ma = trunc(utf8(data, payload, size), 120);
        out.metadata.push({ name: 'mkv_muxing_app', value: ma });
        var c3 = classify(ma);
        if (c3) out.findings.push({ key: 'MKV:MuxingApp', value: ma, kind: c3.kind });
        return false;
      }
      if (id === 0x5741 && size >= 1) {
        var wa = trunc(utf8(data, payload, size), 120);
        out.metadata.push({ name: 'mkv_writing_app', value: wa });
        var c4 = classify(wa);
        if (c4) out.findings.push({ key: 'MKV:WritingApp', value: wa, kind: c4.kind });
        return false;
      }
      if (id === 0xB0 && size >= 1) { out.width = Math.max(out.width || 0, readUint(payload, Math.min(size, 8))); return false; }
      if (id === 0xBA && size >= 1) { out.height = Math.max(out.height || 0, readUint(payload, Math.min(size, 8))); return false; }
      return true;
    });
    if (durationNs != null) out.duration = Math.round(durationNs * ts / 1000000000 * 100) / 100;
    if (tags.length) out.metadata.push({ name: 'mkv_tag_names', value: trunc(tags.join(' | '), 160) });
  }

  /* ================= RIFF (AVI) ================= */
  function riffWalk(data, cb) {
    var n = data.length;
    var view = new DataView(data.buffer, data.byteOffset, data.byteLength);
    if (n < 12 || fourcc(data, 0) !== 'RIFF' || fourcc(data, 8) !== 'AVI ') return;
    (function walk(start, end) {
      var pos = start;
      while (pos + 8 <= end) {
        var id = fourcc(data, pos);
        var size = view.getUint32(pos + 4, true);
        var padded = size + (size & 1);
        if (pos + 8 + padded > end) break;
        if (id === 'LIST') {
          var lt = fourcc(data, pos + 8);
          if (cb('LIST', lt, pos, size, 1) !== false) walk(pos + 12, pos + 8 + padded);
        } else {
          cb(id, null, pos, size, 0);
        }
        pos += 8 + padded;
      }
    })(12, Math.min(8 + view.getUint32(4, true), n));
  }
  function riffStrip(data) {
    var regions = [], removed = [];
    riffWalk(data, function (id, listType, pos, size) {
      if (id === 'LIST' && listType === 'INFO') {
        regions.push([pos, size]);
        removed.push('AVI:INFO');
        return false;
      }
      return true;
    });
    if (!regions.length) return { data: null, removed: [] };
    var out = new Uint8Array(data.length);
    out.set(data);
    for (var r = 0; r < regions.length; r++) {
      var p = regions[r][0], sz = regions[r][1];
      out[p] = 0x4A; out[p + 1] = 0x55; out[p + 2] = 0x4E; out[p + 3] = 0x4B; // 'JUNK'
      for (var i = p + 8; i < p + 8 + sz; i++) out[i] = 0;
    }
    return { data: out, removed: ['AVI:INFO'] };
  }
  function riffScan(data, out) {
    out.kind = 'riff';
    var view = new DataView(data.buffer, data.byteOffset, data.byteLength);
    riffWalk(data, function (id, listType, pos, size, isList) {
      if (isList && listType === 'INFO') {
        // INFO 子块
        var p = pos + 12, end = pos + 8 + size;
        while (p + 8 <= end) {
          var cid = fourcc(data, p);
          var csz = view.getUint32(p + 4, true);
          var cp = csz + (csz & 1);
          if (p + 8 + cp > end) break;
          var text = utf8(data, p + 8, Math.min(csz, 200)).replace(/\0+$/, '');
          var names = { INAM: 'avi_title', IART: 'avi_artist', ICMT: 'avi_comment', ICRD: 'avi_date', ISFT: 'avi_encoder', IENG: 'avi_engineer', ICOP: 'avi_copyright', ITCH: 'avi_technician', IKEY: 'avi_keywords' };
          var nm = names[cid];
          if (nm) {
            out.metadata.push({ name: nm, value: trunc(text, 200) });
            var c = classify(text);
            if (c) out.findings.push({ key: 'AVI:' + cid, value: trunc(text, 120), kind: c.kind });
          }
          p += 8 + cp;
        }
        return false;
      }
      if (!isList && id === 'avih') {
        if (size >= 40) {
          var frames = view.getUint32(pos + 8 + 16, true);
          var usPer = view.getUint32(pos + 8 + 0, true);
          out.width = Math.max(out.width || 0, view.getUint32(pos + 8 + 32, true));
          out.height = Math.max(out.height || 0, view.getUint32(pos + 8 + 36, true));
          if (!out.duration && usPer) out.duration = Math.round(frames * usPer / 10000) / 100;
        }
        return false;
      }
      return true;
    });
  }

  /* ================= 对外 API ================= */
  var VIDEO_EXT = { mp4: 1, mov: 1, m4v: 1, mkv: 1, webm: 1, avi: 1 };
  function detectKind(data) {
    if (data.length >= 12 && fourcc(data, 0) === 'RIFF') {
      if (fourcc(data, 8) === 'AVI ') return 'riff';
      return null;
    }
    if (data.length >= 4 && u32(data, 0) === 0x1A45DFA3) return 'ebml';
    // ISOBMFF: 头部通常为 ftyp/…/moov/mdat/wide/free 之一
    if (data.length >= 12) {
      var t = fourcc(data, 4);
      if (t === 'ftyp' || t === 'moov' || t === 'mdat' || t === 'free' || t === 'skip' || t === 'wide' || t === 'styp' || t === 'pdin') {
        var sz = u32(data, 0);
        if (sz >= 8 && sz <= data.length) return 'isobmff';
      }
    }
    return null;
  }
  function stripVideo(data, ext) {
    var kind = detectKind(data);
    if (!kind) return { data: null, removed: [], kind: null };
    if (kind === 'isobmff') { var r1 = isoStrip(data); return { data: r1.data, removed: r1.removed, kind: kind }; }
    if (kind === 'ebml') { var r2 = ebmlStrip(data); return { data: r2.data, removed: r2.removed, kind: kind }; }
    if (kind === 'riff') { var r3 = riffStrip(data); return { data: r3.data, removed: r3.removed, kind: kind }; }
    return { data: null, removed: [], kind: kind };
  }
  function scanVideo(data, ext) {
    var out = { verdict: 'clean', findings: [], metadata: [], c2pa: false, width: 0, height: 0, duration: 0, kind: null };
    scanC2pa(data, out);
    var kind = detectKind(data);
    if (kind === 'isobmff') isoScan(data, out);
    else if (kind === 'ebml') ebmlScan(data, out);
    else if (kind === 'riff') riffScan(data, out);
    out.verdict = verdictOf(out);
    return out;
  }
  function isVideoExt(ext) { return !!VIDEO_EXT[String(ext || '').toLowerCase()]; }

  var V = {
    detectKind: detectKind, stripVideo: stripVideo, scanVideo: scanVideo,
    isoWalk: isoWalk, ebmlWalk: ebmlWalk, riffWalk: riffWalk, isVideoExt: isVideoExt,
    voidHeader: voidHeader,
  };
  root.MRPVideo = V;
  if (typeof module !== 'undefined' && module.exports) module.exports = V;
})(typeof globalThis !== 'undefined' ? globalThis : this);
